logging:
    level:
      root: INFO

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/to_do_list?useSSL=FALSE&readOnlyPropagatesToServer=false&useUnicode=yes&rewriteBatchedStatements=true
    username: root
    password: root